### ISSUE TITLE
Differential expression outout file error?

### ISSUE THREAD

**Issue by haratoru** [ScienceParkMadrid/SinglePointRNA#2]
Great tool! Thank you for your great work!
When, however, I saved the DE analysis results, the excel file didn't contain the gene names. 
Only the gene names are lost.
Is this a error ? Or do I need to apdate any library?

I look forward to your response.

**Comment by LauraPS1** [comment]
Hi, thanks for trying our app!
Yes, it was an error in the saving function, it has been corrected and it should be working properly now.
Cheers

**Comment by haratoru** [comment]
I truly thank you from the bottom of my heart.

**Comment by haratoru** [comment]
Hi, I have another question.
When I do DE analysis, heatmap is not appear.
And following error messages come.

--------------------------------------------------------------------
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=========================================================================================================================================================| 100%
 DoHeatmap(inputData, features = top, size = 4, raster = TRUE,  Warning message: 
  The following features were omitted as they were not found in the scale.data slot for the RNA assay: NA
--------------------------------------------------------------------

Is this a SCT problem in my file, or another error?

I look forward to your response.

**Comment by LauraPS1** [comment]
Hi!
This error likely happened because there aren't enough up-regulated genes in some of the clusters.

As it was, the function was set to plot the 5 up-regulated genes (over the minimum LFC threshold)  with the lowest p-value for each cluster. If the LFC threshold is high, some clusters might not have enough markers for the heatmap.
I've modified it so it will generate the plot with less than 5 markers per cluster.

**Comment by haratoru** [comment]
Thank you so much. 
Yes. Some clusters didn't have enough markers in my file.

Now I have integrated some  SCT normalized data,  and I have tried to analyse with SinglepointRNA.
Then other error has come up.So I have fixed my integrated file using the following code.
And error does not have happen with this file.
Is this Ok ?

in R------------------------------------------------------------------------
data<-readRDS("SCT_normarized_integrated_file")
VariableFeatures(data[["SCT"]]) <- rownames(data[["SCT"]]@scale.data)
saveRDS(data, file = "fixed_data")

**Comment by LauraPS1** [comment]
No problem!

At which step of the analysis did you find the error?  When doing the integration, was there a particular error or warning message? If so, please paste it here, it would help a lot identifying the issue, since there could be several problems that would be "removed" by setting all scaled genes as variable genes.

**Comment by haratoru** [comment]
Thank you! I'm glad to hear that.

I conducted QC, Filter and Normalization( SCTrasnform ) and saved the data in RDS. 
I repeated this operatin.
Besides, I integrated these RDS file, and Itried to analyse using other option like a Cluster in SinglePointRNA.
That time following error occured.

----------------------------------------------------------
 警告:  Error in : SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<-
  1: shiny::runApp

**Comment by LauraPS1** [comment]
Hi,

When doing the integration, what option did you checked for "type of merge"?
![image](https://github.com/ScienceParkMadrid/SinglePointRNA/assets/10809444/43c2a006-5211-4e7f-9f68-5d1d995ab1ce)

If you selected "simple merge", this option will not perform any additional correction or normalization to the datasets - it just concatenates the data - hence the "multiple SCT models message".
On the other hand, "sample integration" does try to combine the data correcting for batch effects, etc, making different samples (biological replicates, treatments, and so on) comparable.

Unless your samples are technical replicates, I'd recommend to select the "sample integration" option, but if you only intend to concatenate the two raw datasets, it would be preferable to re-run the "filter and normalize" step after merging.

**Comment by haratoru** [comment]
Thank you for explaining in detail.
Although I have selected the "sample integration" option, another error happen.
So I selected  "simple merge". Does this mean my data have anything bad?

警告:  Error in if: the condition has length > 1
  1: shiny::runApp

**Comment by LauraPS1** [comment]
My apologies, that was an error on my end when I last updated the merging script.
I have just fixed it, and it shouldn't throw any more errors.

**Comment by haratoru** [comment]
No problem!
I really appreciate what you've done for me. Thank you. 

I'm a beginner of bioinfo, so this tool is really really helpful.
Thank you for great tool!

**Comment by LauraPS1** [comment]
My pleasure!
I will close this issue now, but don't hesitate to contact again with any issues or questions you may have

Cheers
